import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from '../../components/Pixel/index';
import {COLORS, Fonts} from '../../utils/index';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  headerView: {
    flex: 0.1,
  },
  textStyle: {
    fontSize: hp(2.8),
    color: COLORS.black,
    fontFamily: Fonts.FONTS.PoppinsBold,
  },
  mainView: {
    flex: 0.9,
    alignItems: 'center',
  },
  boxView: {
    width: '97%',
    height: hp(18),
    borderRadius: 8,
    marginTop: hp(3),
    paddingHorizontal: wp(5),
    paddingVertical: hp(2),
    justifyContent: 'space-between',
    alignSelf: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  optionText: {
    fontSize: hp(3.2),
    fontFamily: Fonts.FONTS.PoppinsBold,
    color: COLORS.goldenColor,
    textAlign: 'right',
  },
  subViews: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  roundView: {
    height: wp(20),
    width: wp(20),
    borderRadius: wp(20),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.primary,
  },
  iconStyle1: {
    width: wp(12),
    height: hp(12),
    resizeMode: 'contain',
    borderRadius: 80,
  },
  enquireView: {
    width: '97%',
    height: hp(20),
    borderRadius: 8,
    marginTop: hp(3),
    paddingHorizontal: wp(4),
    paddingVertical: hp(2),
    alignSelf: 'center',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
  },
  noticeView: {
    paddingVertical: hp(1),
    width: '97%',
    alignSelf: 'center',
    borderRadius: 8,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
    marginTop: hp(3),
    paddingHorizontal: wp(4),
  },
  titleText: {
    fontSize: hp(2.4),
    fontFamily: Fonts.FONTS.PoppinsBold,
    color: COLORS.black,
    marginVertical: hp(1.5),
  },
  listView: {
    maxHeight: hp(30),
    minHeight: hp(10),
    width: '98%',
    alignSelf: 'center',
    alignItems: 'center',
  },
  titleView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    height: hp(6),
    paddingHorizontal: wp(4),
  },
  titleListText: {
    fontSize: hp(2),
    fontFamily: Fonts.FONTS.PoppinsBold,
    color: COLORS.black,
  },
  dataView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    height: hp(6),
    paddingLeft: wp(3),
    borderBottomColor: COLORS.greyColor,
    borderBottomWidth: 2,
  },
  dataListText: {
    fontSize: hp(2),
    fontFamily: Fonts.FONTS.PoppinsMedium,
    color: COLORS.black,
  },
  dateBox: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '45%',
    height: hp(3),
  },
  listView1: {
    maxHeight: hp(30),
    minHeight: hp(10),
    width: '100%',
    alignSelf: 'center',
    alignItems: 'center',
  },
  titleView1: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    height: hp(6),
    paddingHorizontal: wp(3),
  },
  titleListText1: {
    fontSize: hp(2),
    fontFamily: Fonts.FONTS.PoppinsBold,
    color: COLORS.black,
    textAlign: 'right',
  },
  dataListText1: {
    fontSize: hp(1.7),
    fontFamily: Fonts.FONTS.PoppinsMedium,
    color: COLORS.black,
    textAlign: 'center',
  },
  dateBox1: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '26%',
    borderRadius: 5,
  },
  dataView1: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    paddingVertical: hp(1),
    backgroundColor: COLORS.greyColor,
  },
  noticeView1: {
    paddingVertical: hp(1),
    width: '97%',
    alignSelf: 'center',
    borderRadius: 8,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
    marginTop: hp(3),
  },
  titleText1: {
    fontSize: hp(2.4),
    fontFamily: Fonts.FONTS.PoppinsBold,
    color: COLORS.black,
    marginVertical: hp(1.5),
    paddingHorizontal: wp(3),
  },
  buttonView: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: hp(3),
    paddingHorizontal: wp(3),
    width: '100%',
  },
  button: {
    alignItems: 'center',
    justifyContent: 'center',
    width: wp(22),
    height: hp(4.5),
    backgroundColor: COLORS.blueColor,
    marginRight: wp(3),
    borderRadius: 5,
  },
  buttonText: {
    fontSize: hp(2),
    fontFamily: Fonts.FONTS.PoppinsBold,
    color: COLORS.white,
  },
  dataFoundView: {
    justifyContent: 'center',
    height: hp(10),
    width: '100%',
    alignItems: 'center',
  },
  dataFoundText: {
    fontSize: hp(2.2),
    fontFamily: Fonts.FONTS.PoppinsBold,
    textAlign: 'center',
    color: COLORS.black,
  },
  nameDataView: {
    flexDirection: 'row',
    alignItems: 'center',
    width: wp(32),
  },
  dataHistoryText1: {
    fontSize: hp(1.8),
    fontFamily: Fonts.FONTS.PoppinsMedium,
    color: COLORS.black,
    width: '44%',
  },
  dataHistoryText2: {
    fontSize: hp(1.8),
    fontFamily: Fonts.FONTS.PoppinsBold,
    color: COLORS.blueColor,
  },
});

export default styles;
